<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZfQYXUg' shared service.

return $this->privates['.service_locator.ZfQYXUg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'registrationStage' => ['privates', '.errored..service_locator.ZfQYXUg.App\\Entity\\ResgistrationStage', NULL, 'Cannot autowire service ".service_locator.ZfQYXUg": it references class "App\\Entity\\ResgistrationStage" but no such service exists.'],
], [
    'manager' => '?',
    'registrationStage' => 'App\\Entity\\ResgistrationStage',
]);
