<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.EoCOyLv' shared service.

return $this->privates['.service_locator.EoCOyLv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contact' => ['privates', '.errored..service_locator.EoCOyLv.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.EoCOyLv": it references class "App\\Entity\\Contact" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'contact' => 'App\\Entity\\Contact',
    'manager' => '?',
]);
