<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ogPaD_l' shared service.

return $this->privates['.service_locator.ogPaD_l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AccountController::login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\AccountController::myAccount' => ['privates', '.service_locator.eLkT6Tb', 'get_ServiceLocator_ELkT6TbService.php', true],
    'App\\Controller\\AccountController::profile' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\AccountController::register' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\AccountController::updatePassword' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\ReservationController::create' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\ReservationController::edit' => ['privates', '.service_locator.xJY1n8m', 'get_ServiceLocator_XJY1n8mService.php', true],
    'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.eH1R0Zw', 'get_ServiceLocator_EH1R0ZwService.php', true],
    'App\\Controller\\UserController::index' => ['privates', '.service_locator.eLkT6Tb', 'get_ServiceLocator_ELkT6TbService.php', true],
    'App\\Controller\\AccountController:login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\AccountController:myAccount' => ['privates', '.service_locator.eLkT6Tb', 'get_ServiceLocator_ELkT6TbService.php', true],
    'App\\Controller\\AccountController:profile' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\AccountController:register' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\AccountController:updatePassword' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\ReservationController:create' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\ReservationController:edit' => ['privates', '.service_locator.xJY1n8m', 'get_ServiceLocator_XJY1n8mService.php', true],
    'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.eH1R0Zw', 'get_ServiceLocator_EH1R0ZwService.php', true],
    'App\\Controller\\UserController:index' => ['privates', '.service_locator.eLkT6Tb', 'get_ServiceLocator_ELkT6TbService.php', true],
], [
    'App\\Controller\\AccountController::login' => '?',
    'App\\Controller\\AccountController::myAccount' => '?',
    'App\\Controller\\AccountController::profile' => '?',
    'App\\Controller\\AccountController::register' => '?',
    'App\\Controller\\AccountController::updatePassword' => '?',
    'App\\Controller\\ReservationController::create' => '?',
    'App\\Controller\\ReservationController::edit' => '?',
    'App\\Controller\\ReservationController::show' => '?',
    'App\\Controller\\UserController::index' => '?',
    'App\\Controller\\AccountController:login' => '?',
    'App\\Controller\\AccountController:myAccount' => '?',
    'App\\Controller\\AccountController:profile' => '?',
    'App\\Controller\\AccountController:register' => '?',
    'App\\Controller\\AccountController:updatePassword' => '?',
    'App\\Controller\\ReservationController:create' => '?',
    'App\\Controller\\ReservationController:edit' => '?',
    'App\\Controller\\ReservationController:show' => '?',
    'App\\Controller\\UserController:index' => '?',
]);
