<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.w_YMdhQ' shared service.

return $this->privates['.service_locator.w_YMdhQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repo' => ['privates', 'App\\Repository\\AdherentRepository', 'getAdherentRepositoryService.php', true],
], [
    'repo' => 'App\\Repository\\AdherentRepository',
]);
