<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MkuOmxw' shared service.

return $this->privates['.service_locator.MkuOmxw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.eH1R0Zw', 'get_ServiceLocator_EH1R0ZwService.php', true],
    'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.eH1R0Zw', 'get_ServiceLocator_EH1R0ZwService.php', true],
], [
    'App\\Controller\\ReservationController::show' => '?',
    'App\\Controller\\ReservationController:show' => '?',
]);
