<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xJY1n8m' shared service.

return $this->privates['.service_locator.xJY1n8m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'reservation' => ['privates', '.errored..service_locator.xJY1n8m.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.xJY1n8m": it references class "App\\Entity\\Reservation" but no such service exists.'],
], [
    'manager' => '?',
    'reservation' => 'App\\Entity\\Reservation',
]);
