<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.eLkT6Tb' shared service.

return $this->privates['.service_locator.eLkT6Tb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'adherent' => ['privates', '.errored..service_locator.eLkT6Tb.App\\Entity\\Adherent', NULL, 'Cannot autowire service ".service_locator.eLkT6Tb": it references class "App\\Entity\\Adherent" but no such service exists.'],
], [
    'adherent' => 'App\\Entity\\Adherent',
]);
