<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6GO0nSZ' shared service.

return $this->privates['.service_locator.6GO0nSZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pagination' => ['privates', 'App\\service\\Pagination', 'getPaginationService.php', true],
    'repo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService.php', true],
], [
    'pagination' => 'App\\service\\Pagination',
    'repo' => 'App\\Repository\\ReservationRepository',
]);
