<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\service\Pagination' shared autowired service.

include_once $this->targetDirs[3].'/src/service/Pagination.php';

return $this->privates['App\\service\\Pagination'] = new \App\service\Pagination(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
