<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQZVUkIh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQZVUkIh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQZVUkIh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQZVUkIh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQZVUkIh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QZVUkIh',
    'container.build_id' => 'de83033b',
    'container.build_time' => 1571226674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQZVUkIh');
