<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWLQ8a1N\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWLQ8a1N/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWLQ8a1N.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWLQ8a1N\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWLQ8a1N\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WLQ8a1N',
    'container.build_id' => 'd1a4dd91',
    'container.build_time' => 1571839876,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWLQ8a1N');
