<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJNCrnYk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJNCrnYk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJNCrnYk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJNCrnYk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJNCrnYk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JNCrnYk',
    'container.build_id' => 'a57478e9',
    'container.build_time' => 1570724227,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJNCrnYk');
